services:
  - type: web
    name: mpt-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mpt-backend.onrender.com
    autoDeploy: true
