#!/bin/bash

echo "🚀 Deploying Frontend to Render..."
echo "===================================="

echo "✅ Your build files are ready in ./build/"
echo "✅ Your render.yaml is configured for both services"
echo ""
echo "🌐 Next Steps for Render Deployment:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Sign in to your existing account"
echo "3. Click 'New +' → 'Static Site'"
echo "4. Choose deployment method:"
echo "   - Option A: Connect GitHub repo (if you want source building)"
echo "   - Option B: Manual upload (recommended for privacy)"
echo "5. Configure settings:"
echo "   - Name: mpt-react-frontend"
echo "   - Choose 'Deploy from local directory' (if available)"
echo "   - OR upload your build folder directly"
echo "   - No build command needed - files are ready"
echo ""
echo "6. Add Environment Variable:"
echo "   Key: REACT_APP_API_URL"
echo "   Value: https://mp-xkhc.onrender.com"
echo ""
echo "7. Click 'Create Static Site'"
echo ""
echo "🔗 Your complete setup will be:"
echo "   - Backend: https://mp-xkhc.onrender.com"
echo "   - Frontend: https://mpt-react-frontend.onrender.com"
echo ""
echo "🎯 Ready to deploy on Render!"
echo "🔒 Your source code stays private!"
