#!/bin/bash

echo "🚀 Deploying MPT React Frontend to Render!"
echo "============================================="

echo "📦 Your React app is ready for Render deployment!"
echo ""
echo "🌐 To deploy to Render:"
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Select this 'clean-react-frontend' repository"
echo "6. Render will auto-detect it's a React app"
echo "7. Click 'Create Web Service'"
echo ""
echo "✅ Render will automatically:"
echo "   - Install dependencies (npm install)"
echo "   - Build your app (npm run build)"
echo "   - Start your app (npm start)"
echo "   - Give you a live URL!"
echo ""
echo "🎯 Your complete web app will be:"
echo "   - Frontend: Render (React)"
echo "   - Backend: Railway (Spring Boot)"
echo ""
echo "🚀 Ready to deploy! Go to https://render.com now!"
