[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/mpt-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
SPRING_PROFILES_ACTIVE = "railway"
JAVA_VERSION = "17"
PORT = "8080"
