services:
  # Backend Service (Spring Boot API)
  - type: web
    name: mpt-backend
    env: java
    buildCommand: |
      export MAVEN_OPTS="-Xmx1024m"
      cd clean-spring-boot
      chmod +x ./mvnw
      ./mvnw clean package -DskipTests
    startCommand: |
      cd clean-spring-boot
      java -Xmx512m -jar target/mpt-0.0.1-SNAPSHOT.jar --server.port=$PORT --spring.profiles.active=render
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SERVER_PORT
        value: $PORT
      - key: JAVA_VERSION
        value: 17
    healthCheckPath: /api/health
    autoDeploy: true
    dockerfilePath: ""

  # Frontend Service (React App)  
  - type: static
    name: mpt-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mpt-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true