services:
  # Frontend Service (React)
  - type: web
    name: mpt-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://mpt-backend.onrender.com
    staticPublishPath: ./build
