services:
  - type: web
    name: mpt-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/mpt-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
