services:
  # Frontend Service (React)
  - type: static
    name: mpt-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://mpt-backend.onrender.com
    autoDeploy: true
