name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Backend
        run: |
          echo "Building Spring Boot backend..."
          cd backend
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests
          echo "Backend build completed successfully!"
          ls -la target/
          
      - name: Deploy Backend to Render
        run: |
          echo "Backend built successfully!"
          echo "Manual deployment to Render required for now"
          echo "Your backend JAR is ready in backend/target/"
          echo "JAR file size: $(du -h backend/target/*.jar | head -1)"
          
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Frontend Dependencies
        run: |
          echo "Installing frontend dependencies..."
          cd frontend
          npm install
          echo "Dependencies installed successfully!"
          
      - name: Build Frontend
        run: |
          echo "Building React frontend..."
          cd frontend
          npm run build
          echo "Frontend build completed successfully!"
          ls -la build/
          
      - name: Deploy Frontend to Render
        run: |
          echo "Frontend built successfully!"
          echo "Manual deployment to Render required for now"
          echo "Your frontend build is ready in frontend/build/"
          echo "Build directory size: $(du -sh frontend/build/)"
          
      - name: Show Build Results
        run: |
          echo "=== BUILD SUMMARY ==="
          echo "Backend: ✅ Built successfully"
          echo "Frontend: ✅ Built successfully"
          echo "Both applications are ready for deployment!"
          echo "Check your Render dashboard to deploy manually"
          echo ""
          echo "📱 Backend JAR: backend/target/mpt-0.0.1-SNAPSHOT.jar"
          echo "🌐 Frontend Build: frontend/build/"
          echo ""
          echo "🚀 Next steps:"
          echo "1. Go to Render dashboard"
          echo "2. Update your services with these build outputs"
          echo "3. Or wait for manual deployment"
